build:
  cuda_version: "12.1.1"
  python_packages:
    - "accelerate==1.3.0"
    - "diffusers==0.32.2"
    - "transformers==4.48.3"
    - "torch==2.6.0"
    - "sentencepiece==0.2.0"
    - "protobuf==5.29.3"
    - "huggingface-hub==0.25.2"